### ISSUE TITLE
Read me

### ISSUE THREAD

**Issue by AntonNix** [recoveryrecord/SurveyNative#4]
Maybe that's my issues with a browser or etc. but 

" single_select screenshot | json "
Screenshot and json pointing on the same hyperlink "https://github.com/recoveryrecord/SurveyNative#single_select". Is it a right behavior?

Browser Google Chrome Version 58.0.3029.110 (64-bit).
MacOS Sierra v. 10.12.3 (16D32)

**Comment by AntonNix** [comment]
Sorry for not so important statement, but in the sentence "Weight must be less than 250cm" maybe mean Height. Just want to improve this good feature.

**Comment by stuartrr** [comment]
> "https://github.com/recoveryrecord/SurveyNative#single_select". Is it a right behavior?

We haven't added screenshots yet. I'll add some today or tomorrow and update the old video capture.

> Weight must be less than 250cm

Good catch. Will fix today or tomorrow.

**Comment by AntonNix** [comment]
Thank you for so fast response. Great feature. Great job.
