### ISSUE TITLE
"show_if" does not work in "sub_questions"

### ISSUE THREAD

**Issue by mauricecheung** [recoveryrecord/SurveyNative#5]
A sub-question in "sub_questions" does not show as expected when the condition in "show_if" field of the sub-question is met. Below is a concrete example of the issue when running the questions in ExampleQuestions.json.
![untitled 2](https://user-images.githubusercontent.com/11825432/37616222-9cb00e50-2b85-11e8-9ccd-c72b71472beb.png)
According to the logic of the JSON, the sub-question "Which sports do you like to play?" will show if "Yes" is selected. However, it is not showing, as seen in the screenshot.

**Comment by nmullaney** [comment]
I left for maternity leave suddenly and forgot about this issue.  It is fixed in the latest release (0.2.0).  Apologies for the long delay!
